/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.HospitalDataRecord;
import model.HospitalDetails;

/**
 *
 * @author deepaksharma
 */
public class AddNewHospitalDetails extends javax.swing.JPanel {

    /**
     * Creates new form AddNewHospitalDetails
     */
    HospitalDataRecord hospital_history;
    public AddNewHospitalDetails(HospitalDataRecord hospital_history) {
        initComponents();
        this.hospital_history = hospital_history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HospitalIDTxt = new javax.swing.JTextField();
        HospitalNameLabel = new javax.swing.JLabel();
        HospitalNameTxt = new javax.swing.JTextField();
        HospitalContactLabel = new javax.swing.JLabel();
        HospitalContactTxt = new javax.swing.JTextField();
        HospitalEmailLabel = new javax.swing.JLabel();
        HospitalEmailTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        HospitalStreetNameLabel = new javax.swing.JLabel();
        HospitalStreetNameTxt = new javax.swing.JTextField();
        HospitalCityLabel = new javax.swing.JLabel();
        HospitalCityTxt = new javax.swing.JTextField();
        HospitalCountryLabel = new javax.swing.JLabel();
        HospitalCountryTxt = new javax.swing.JTextField();
        HospitalPostalCodeLabel = new javax.swing.JLabel();
        HospitalPostalCodeTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Hospital Details");

        jLabel3.setText("ID*:");

        HospitalIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalIDTxtActionPerformed(evt);
            }
        });

        HospitalNameLabel.setText("Name*:");

        HospitalContactLabel.setText("Contact:");

        HospitalContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalContactTxtActionPerformed(evt);
            }
        });

        HospitalEmailLabel.setText("Email:");

        HospitalEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalEmailTxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Address:");

        HospitalStreetNameLabel.setText("Street Name:");

        HospitalStreetNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalStreetNameTxtActionPerformed(evt);
            }
        });

        HospitalCityLabel.setText("City*:");

        HospitalCountryLabel.setText("Country:");

        HospitalPostalCodeLabel.setText("Postal Code:");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 3, 12)); // NOI18N
        jLabel2.setText("* Mandatory Parameters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HospitalEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(HospitalNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospitalContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HospitalContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospitalNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospitalIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HospitalEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HospitalPostalCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalStreetNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HospitalStreetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalPostalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(137, 137, 137))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HospitalStreetNameLabel)
                                .addComponent(HospitalStreetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HospitalCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospitalCityLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HospitalCountryLabel)
                                .addComponent(HospitalCountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HospitalPostalCodeLabel)
                                .addComponent(HospitalPostalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HospitalIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalNameLabel)
                            .addComponent(HospitalNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalContactLabel)
                            .addComponent(HospitalContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalEmailLabel)
                            .addComponent(HospitalEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(315, 315, 315))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HospitalIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalIDTxtActionPerformed

    private void HospitalContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalContactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalContactTxtActionPerformed

    private void HospitalStreetNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalStreetNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalStreetNameTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String validate_hospital_id = String.valueOf(HospitalIDTxt.getText());
         if (validate_hospital_id.length() == 0 ){
            JOptionPane.showMessageDialog(this,"The 'ID' is a mandatory field, please provide required value.", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (validate_hospital_id.length() > 0 ){
            try 
                { 
                Integer.parseInt(HospitalIDTxt.getText()); 
                }  
            catch (NumberFormatException e)  
                { 
                JOptionPane.showMessageDialog(this,"The ID is invalid, please provide the integer value only.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;}          
        } 
        
        
        
        String name = HospitalNameTxt.getText();
        if (name.length() == 0 ){
            JOptionPane.showMessageDialog(this,"The 'Name' is a mandatory field, please provide required value.", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String validate_hosp_contact = String.valueOf(HospitalContactTxt.getText());
        if (validate_hosp_contact.length() > 0 ){
            try 
                { 
                Long.parseLong(HospitalContactTxt.getText()); 
                }  
            catch (NumberFormatException e)  
                { 
                JOptionPane.showMessageDialog(this,"The Contact is invalid, please provide the integer value only.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;}          
        } 
        
        String city = HospitalCityTxt.getText();
        if (city.length() == 0 ){
            JOptionPane.showMessageDialog(this,"The 'City' is a mandatory field, please provide required value.", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (validate_hosp_contact.length() != 10 ){
                JOptionPane.showMessageDialog(this,"The Contact is invalid, please provide the valid contact value.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;
        }
        
        
        String validate_hosp_mail = String.valueOf(HospitalEmailTxt.getText());
        if (!validate_hosp_mail.contains("@") && validate_hosp_mail.length() > 0  ){
            JOptionPane.showMessageDialog(this,"The email is invalid, please provide the valid mail id.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
            return;     
        } 
        
        
        int hospital_id = Integer.parseInt(HospitalIDTxt.getText());
        String hospital_name = HospitalNameTxt.getText();
        long hospital_contact = Long.parseLong(HospitalContactTxt.getText());
        String hospital_email = HospitalEmailTxt.getText();
        String hospital_streetname = HospitalStreetNameTxt.getText();
        String hospital_city = HospitalCityTxt.getText();
        String hospital_country = HospitalCountryTxt.getText();
        String hospital_postalcode = HospitalPostalCodeTxt.getText();
        
        for (HospitalDetails ed : hospital_history.getHistory()){
        int history_hospital_id = ed.getHospital_id();
        if (hospital_id == history_hospital_id){     
            JOptionPane.showMessageDialog(this,"The 'ID' is already exist, please provide the another value.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
            return;
            }
        }
        
        HospitalDetails HospRec = hospital_history.addNewHospital();       
        HospRec.setHospital_name(hospital_name);
        HospRec.setHospital_id(hospital_id);
        HospRec.setHospital_contact(hospital_contact);
        HospRec.setHospital_email(hospital_email);
        HospRec.setHospital_city(hospital_city);
        HospRec.setHospital_country(hospital_country);
        HospRec.setHospital_postal_code(hospital_postalcode);
        HospRec.setHospital_street_name(hospital_streetname);
        
        JOptionPane.showMessageDialog(this, "The Hospital Details has been saved");

        HospitalIDTxt.setText("");
        HospitalNameTxt.setText("");
        HospitalContactTxt.setText("");
        HospitalEmailTxt.setText("");
        HospitalStreetNameTxt.setText("");
        HospitalCityTxt.setText("");
        HospitalCountryTxt.setText("");
        HospitalPostalCodeTxt.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HospitalEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalEmailTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HospitalCityLabel;
    private javax.swing.JTextField HospitalCityTxt;
    private javax.swing.JLabel HospitalContactLabel;
    private javax.swing.JTextField HospitalContactTxt;
    private javax.swing.JLabel HospitalCountryLabel;
    private javax.swing.JTextField HospitalCountryTxt;
    private javax.swing.JLabel HospitalEmailLabel;
    private javax.swing.JTextField HospitalEmailTxt;
    private javax.swing.JTextField HospitalIDTxt;
    private javax.swing.JLabel HospitalNameLabel;
    private javax.swing.JTextField HospitalNameTxt;
    private javax.swing.JLabel HospitalPostalCodeLabel;
    private javax.swing.JTextField HospitalPostalCodeTxt;
    private javax.swing.JLabel HospitalStreetNameLabel;
    private javax.swing.JTextField HospitalStreetNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
