/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DoctorDataRecord;
import model.DoctorDetails;
import model.HospitalDataRecord;
import model.HospitalDetails;

/**
 *
 * @author deepaksharma
 */
public class PatientHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientHomeJPanel
     */
   
    HospitalDataRecord hospital_history;
    DoctorDataRecord doctor_history;
    public PatientHomeJPanel(HospitalDataRecord hospital_history, DoctorDataRecord doctor_history) {
        initComponents();
        this.hospital_history = hospital_history;
        this.doctor_history = doctor_history;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        PatientLabelJPanel = new javax.swing.JLabel();
        PatientWorkingJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CitySearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HospitalTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DoctorNameTxt = new javax.swing.JTextField();
        DoctorIDLabel = new javax.swing.JLabel();
        DoctorNameLabel = new javax.swing.JLabel();
        DoctorContactTxt = new javax.swing.JTextField();
        DoctorEmailTxt = new javax.swing.JTextField();
        DoctorEmailLabel = new javax.swing.JLabel();
        DoctorAssignedHospitalIDLabel = new javax.swing.JLabel();
        DoctorContactLabel = new javax.swing.JLabel();
        DoctorSpecialityTxt = new javax.swing.JTextField();
        DoctorAssignedHospitalIDTxt = new javax.swing.JTextField();
        DoctorSpecialityLabel = new javax.swing.JLabel();
        DoctorGenderTxt = new javax.swing.JTextField();
        DoctorGenderLabel = new javax.swing.JLabel();
        DoctorIDTxt = new javax.swing.JTextField();

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        PatientLabelJPanel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        PatientLabelJPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PatientLabelJPanel.setText("PATIENT");

        jLabel3.setText("Nearest Hospital City :");

        CitySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitySearchActionPerformed(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        HospitalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Contact", "City", "Country"
            }
        ));
        jScrollPane1.setViewportView(HospitalTable);

        jButton2.setText("VIEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Doctor Details ");

        DoctorNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameTxtActionPerformed(evt);
            }
        });

        DoctorIDLabel.setText("ID*:");

        DoctorNameLabel.setText("Name*:");

        DoctorContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactTxtActionPerformed(evt);
            }
        });

        DoctorEmailLabel.setText("Email:");

        DoctorAssignedHospitalIDLabel.setText("Assigned Hospital ID*:");

        DoctorContactLabel.setText("Contact:");

        DoctorAssignedHospitalIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorAssignedHospitalIDTxtActionPerformed(evt);
            }
        });

        DoctorSpecialityLabel.setText("Speciality:");

        DoctorGenderLabel.setText("Gender:");

        DoctorIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorIDTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientWorkingJPanelLayout = new javax.swing.GroupLayout(PatientWorkingJPanel);
        PatientWorkingJPanel.setLayout(PatientWorkingJPanelLayout);
        PatientWorkingJPanelLayout.setHorizontalGroup(
            PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientWorkingJPanelLayout.createSequentialGroup()
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientWorkingJPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(PatientWorkingJPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientWorkingJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorAssignedHospitalIDLabel)
                    .addComponent(DoctorSpecialityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorContactLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorAssignedHospitalIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorSpecialityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(241, 241, 241))
        );
        PatientWorkingJPanelLayout.setVerticalGroup(
            PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientWorkingJPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(CitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorIDLabel))
                .addGap(7, 7, 7)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorNameLabel)
                    .addComponent(DoctorNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorGenderLabel)
                    .addComponent(DoctorGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorSpecialityLabel)
                    .addComponent(DoctorSpecialityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorAssignedHospitalIDLabel)
                    .addComponent(DoctorAssignedHospitalIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorEmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PatientWorkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatientLabelJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatientWorkingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PatientLabelJPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientWorkingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SplitPane.setTopComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CitySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitySearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CitySearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user_search_city = CitySearch.getText();
        
        DefaultTableModel model = (DefaultTableModel) HospitalTable.getModel();
        model.setRowCount(0);
        for (HospitalDetails ed : hospital_history.getHistory()){
            if (ed.getHospital_city() == null ? user_search_city == null : ed.getHospital_city().equals(user_search_city) ){
                try 
                { 
                    Object[] row = new Object[5];
                    row[0] = ed;
                    row[1] = ed.getHospital_id();
                    row[2] = ed.getHospital_contact();
                    row[3] = ed.getHospital_city();
                    row[4] = ed.getHospital_country();
                    model.addRow(row);
                }  
            catch (NumberFormatException e)  
                { 
                JOptionPane.showMessageDialog(this,"The Hospital City doesn't registered in the system, please provide the register cities only.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;
                }       
        }

    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        int SelectedRowIndex = HospitalTable.getSelectedRow();

        if (SelectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a record to view details");
            return;
        }

        DefaultTableModel model = (DefaultTableModel)HospitalTable.getModel();
        HospitalDetails SelectedHospRecord = (HospitalDetails) model.getValueAt(SelectedRowIndex, 0);
        
        int user_selected_hospital_id = SelectedHospRecord.getHospital_id();
        
        int id_check = 0 ;
        for (DoctorDetails ed : doctor_history.getHistory()){
            int hosp_doc_id = ed.getDoctor_assigned_hospital_id(); 
            if (hosp_doc_id == user_selected_hospital_id){
                id_check = 1;                  
                DoctorNameTxt.setText(ed.getDoctor_name());
                DoctorIDTxt.setText(String.valueOf(ed.getDoctor_id()));
                DoctorGenderTxt.setText(ed.getDoctor_gender());
                DoctorSpecialityTxt.setText(ed.getDoctor_speciality());
                DoctorAssignedHospitalIDTxt.setText(String.valueOf(ed.getDoctor_assigned_hospital_id()));
                DoctorEmailTxt.setText(ed.getDoctor_email());
                DoctorContactTxt.setText(String.valueOf(ed.getDoctor_contact()));
            }
        }

        if (id_check != 1 ){
            JOptionPane.showMessageDialog(this,"The Doctor doesn't registered for the selected hospital", "Invalid Value", JOptionPane.WARNING_MESSAGE);
            return;
        }   
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DoctorNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameTxtActionPerformed

    private void DoctorContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactTxtActionPerformed

    private void DoctorAssignedHospitalIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorAssignedHospitalIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorAssignedHospitalIDTxtActionPerformed

    private void DoctorIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorIDTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CitySearch;
    private javax.swing.JLabel DoctorAssignedHospitalIDLabel;
    private javax.swing.JTextField DoctorAssignedHospitalIDTxt;
    private javax.swing.JLabel DoctorContactLabel;
    private javax.swing.JTextField DoctorContactTxt;
    private javax.swing.JLabel DoctorEmailLabel;
    private javax.swing.JTextField DoctorEmailTxt;
    private javax.swing.JLabel DoctorGenderLabel;
    private javax.swing.JTextField DoctorGenderTxt;
    private javax.swing.JLabel DoctorIDLabel;
    private javax.swing.JTextField DoctorIDTxt;
    private javax.swing.JLabel DoctorNameLabel;
    private javax.swing.JTextField DoctorNameTxt;
    private javax.swing.JLabel DoctorSpecialityLabel;
    private javax.swing.JTextField DoctorSpecialityTxt;
    private javax.swing.JTable HospitalTable;
    private javax.swing.JLabel PatientLabelJPanel;
    private javax.swing.JPanel PatientWorkingJPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
