/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.DoctorDetails;
import model.MedcareDataRecord;
import model.PatientDataRecord;
import model.PatientDetails;

/**
 *
 * @author deepaksharma
 */
public class UpdatePatientDetails extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePatientDetails
     */
    PatientDataRecord patient_history ;
    public UpdatePatientDetails(PatientDataRecord patient_history) {
        initComponents();
        this.patient_history = patient_history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TxtPatientIDSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PatientGenderLabel = new javax.swing.JLabel();
        PatientBloodPressureLabel = new javax.swing.JLabel();
        PatientNameTxt = new javax.swing.JTextField();
        PatientPostalCodeTxt = new javax.swing.JTextField();
        PatientNameLabel = new javax.swing.JLabel();
        PatientPostalCodeLabel = new javax.swing.JLabel();
        PatientCountryTxt = new javax.swing.JTextField();
        PatientCountryLabel = new javax.swing.JLabel();
        PatientIDTxt = new javax.swing.JTextField();
        PatientCityTxt = new javax.swing.JTextField();
        PatientCityLabel = new javax.swing.JLabel();
        PatientIDLabel = new javax.swing.JLabel();
        PatientStreetNameTxt = new javax.swing.JTextField();
        PatientEmailLabel = new javax.swing.JLabel();
        PatientStreetNameLabel = new javax.swing.JLabel();
        PatientContactTxt = new javax.swing.JTextField();
        PatientHNOTxt = new javax.swing.JTextField();
        PatientMedicalHistoryLabel = new javax.swing.JLabel();
        PatientHNOLabel = new javax.swing.JLabel();
        PatientContactLabel = new javax.swing.JLabel();
        PatientMedicalHistoryTxt = new javax.swing.JTextField();
        PatientAgeTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PatientDiagnosisTxt = new javax.swing.JTextField();
        PatientDiagnosisLabel = new javax.swing.JLabel();
        PatientBloodGroupTxt = new javax.swing.JTextField();
        PatientEmailTxt = new javax.swing.JTextField();
        PatientAgeLabel = new javax.swing.JLabel();
        PatientBodyTempLabel = new javax.swing.JLabel();
        PatientBodyTempTxt = new javax.swing.JTextField();
        PatientBloodGroupLabel = new javax.swing.JLabel();
        PatientGenderTxt = new javax.swing.JTextField();
        PatientBloodPressureTxt = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Patient Details");

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Patient ID:");

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TxtPatientIDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPatientIDSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 3, 12)); // NOI18N
        jLabel2.setText("* Mandatory Parameters");

        PatientGenderLabel.setText("Gender:");

        PatientBloodPressureLabel.setText("Blood Pressure:");

        PatientNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientNameTxtActionPerformed(evt);
            }
        });

        PatientNameLabel.setText("Name*:");

        PatientPostalCodeLabel.setText("Postal Code:");

        PatientCountryLabel.setText("Country:");

        PatientIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIDTxtActionPerformed(evt);
            }
        });

        PatientCityLabel.setText("City:");

        PatientIDLabel.setText("ID*:");

        PatientStreetNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientStreetNameTxtActionPerformed(evt);
            }
        });

        PatientEmailLabel.setText("Email:");

        PatientStreetNameLabel.setText("Street Name:");

        PatientContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientContactTxtActionPerformed(evt);
            }
        });

        PatientMedicalHistoryLabel.setText("Medical History:");

        PatientHNOLabel.setText("H.No:");

        PatientContactLabel.setText("Contact*:");

        jLabel10.setText("Address:");

        PatientDiagnosisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientDiagnosisTxtActionPerformed(evt);
            }
        });

        PatientDiagnosisLabel.setText("Diagnosis:");

        PatientBloodGroupTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientBloodGroupTxtActionPerformed(evt);
            }
        });

        PatientAgeLabel.setText("Age*:");

        PatientBodyTempLabel.setText("Body Temperature:");

        PatientBloodGroupLabel.setText("Blood Group:");

        PatientBloodPressureTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientBloodPressureTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPatientIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(PatientAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PatientDiagnosisLabel)
                                        .addComponent(PatientContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PatientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PatientEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientDiagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PatientHNOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PatientPostalCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PatientCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PatientCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PatientStreetNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PatientStreetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientHNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientCountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientPostalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PatientBodyTempLabel)
                                            .addComponent(PatientMedicalHistoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientBloodGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientBloodPressureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(PatientBodyTempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientBloodPressureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientBloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientMedicalHistoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(TxtPatientIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientIDLabel))
                        .addGap(2, 2, 2))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientHNOLabel)
                            .addComponent(PatientHNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientStreetNameLabel)
                            .addComponent(PatientStreetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientCityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientCountryLabel)
                            .addComponent(PatientCountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientPostalCodeLabel)
                            .addComponent(PatientPostalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientBloodPressureLabel)
                            .addComponent(PatientBloodPressureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientBodyTempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientBodyTempLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientBloodGroupLabel)
                            .addComponent(PatientBloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientMedicalHistoryLabel)
                            .addComponent(PatientMedicalHistoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientNameLabel)
                            .addComponent(PatientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientGenderLabel)
                            .addComponent(PatientGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientAgeLabel)
                            .addComponent(PatientAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientContactLabel)
                            .addComponent(PatientContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientEmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientDiagnosisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientDiagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String patient_id = String.valueOf(TxtPatientIDSearch.getText());
        
        if (patient_id.length() == 0 ){
            JOptionPane.showMessageDialog(this,"The search field is empty, please provide required values to search.", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (patient_id.length() > 0 ){
            try 
                { 
                int user_patient_id = Integer.parseInt(TxtPatientIDSearch.getText()); 
                }  
            catch (NumberFormatException e)  
                { 
                JOptionPane.showMessageDialog(this,"The Patient ID is invalid, please provide the integer value only.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;}          
        } 
        
        PatientAgeTxt.setText("");
        PatientBloodGroupTxt.setText("");
        PatientBloodPressureTxt.setText("");
        PatientBodyTempTxt.setText("");
        PatientCityTxt.setText("");
        PatientContactTxt.setText("");
        PatientCountryTxt.setText("");
        PatientDiagnosisTxt.setText("");
        PatientEmailTxt.setText("");
        PatientGenderTxt.setText("");
        PatientHNOTxt.setText("");
        PatientIDTxt.setText("");
        PatientMedicalHistoryTxt.setText("");
        PatientNameTxt.setText("");
        PatientPostalCodeTxt.setText("");
        PatientStreetNameTxt.setText("");
        
        
        int user_patient_id = Integer.parseInt(TxtPatientIDSearch.getText());
        int id_check = 0 ;
        for (PatientDetails ed : patient_history.getHistory()){
            int pat_id = ed.getPatient_id(); 
            if (pat_id == user_patient_id){
                id_check = 1;                  
                PatientNameTxt.setText(ed.getPatient_name());
                PatientIDTxt.setText(String.valueOf(ed.getPatient_id()));
                PatientGenderTxt.setText(ed.getPatient_gender());
                PatientAgeTxt.setText(String.valueOf(ed.getPatient_age()));
                PatientBloodGroupTxt.setText(String.valueOf(ed.getPatient_bloodgroup()));                
                PatientBloodPressureTxt.setText(String.valueOf(ed.getPatient_bloodpressure()));                 
                PatientBodyTempTxt.setText(String.valueOf(ed.getPatient_bodytemp()));
                PatientCityTxt.setText(ed.getPatient_city());
                PatientContactTxt.setText(String.valueOf(ed.getPatient_contact()));
                PatientCountryTxt.setText(ed.getPatient_country());
                PatientDiagnosisTxt.setText(ed.getPatient_diagnosis());
                PatientEmailTxt.setText(ed.getPatient_email());
                PatientHNOTxt.setText(String.valueOf(ed.getPatient_house_no()));             
                PatientMedicalHistoryTxt.setText(ed.getPatient_medicalhistory());
                PatientPostalCodeTxt.setText(ed.getPatient_postal_code());
                PatientStreetNameTxt.setText(ed.getPatient_street_name());
                
            }
        }

        if (id_check != 1 ){
            JOptionPane.showMessageDialog(this,"The Patient ID doesn't exist, please provide correct Patient ID.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
            return;
        }   
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        int update_patient_id = Integer.parseInt(PatientIDTxt.getText()); 
        for (PatientDetails ed : patient_history.getHistory()){
            int pat_id = ed.getPatient_id();
            if (update_patient_id == pat_id){     
                
            int patient_id = Integer.parseInt(PatientIDTxt.getText());
            String patient_name = PatientNameTxt.getText();
            String patient_gender = PatientGenderTxt.getText();
            int patient_age = Integer.parseInt(PatientAgeTxt.getText());
            long patient_contact = Long.parseLong(PatientContactTxt.getText());
            String patient_email = PatientEmailTxt.getText();
            String patient_diagnosis = PatientDiagnosisTxt.getText();
            int patient_hno = Integer.parseInt(PatientHNOTxt.getText());
            String patient_streetname = PatientStreetNameTxt.getText();
            String patient_city = PatientCityTxt.getText();
            String patient_country = PatientCountryTxt.getText();
            String patient_postalcode = PatientPostalCodeTxt.getText();
            int patient_bp = Integer.parseInt(PatientBloodPressureTxt.getText());
            int patient_temp = Integer.parseInt(PatientBodyTempTxt.getText());
            String patient_bloodgrp = PatientBloodGroupTxt.getText();
            String patient_medical_history = PatientMedicalHistoryTxt.getText();
             
                          
                PatientDetails UpdatePatRec = patient_history.UpdatePatient();
                
                UpdatePatRec.setPatient_name(patient_name);
                UpdatePatRec.setPatient_id(patient_id);
                UpdatePatRec.setPatient_age(patient_age);
                UpdatePatRec.setPatient_gender(patient_gender);
                UpdatePatRec.setPatient_contact(patient_contact);
                UpdatePatRec.setPatient_email(patient_email);
                UpdatePatRec.setPatient_diagnosis(patient_diagnosis);
                UpdatePatRec.setPatient_house_no(patient_hno);
                UpdatePatRec.setPatient_street_name(patient_streetname);
                UpdatePatRec.setPatient_city(patient_city);
                UpdatePatRec.setPatient_country(patient_country);
                UpdatePatRec.setPatient_postal_code(patient_postalcode);
                UpdatePatRec.setPatient_bloodpressure(patient_bp);
                UpdatePatRec.setPatient_bodytemp(patient_temp);
                UpdatePatRec.setPatient_bloodgroup(patient_bloodgrp);
                UpdatePatRec.setPatient_medicalhistory(patient_medical_history);
                
                JOptionPane.showMessageDialog(this, "Patient Details has been updated");
                
                patient_history.DeletePatientDetails(ed);
                
                PatientAgeTxt.setText("");
                PatientBloodGroupTxt.setText("");
                PatientBloodPressureTxt.setText("");
                PatientBodyTempTxt.setText("");
                PatientCityTxt.setText("");
                PatientContactTxt.setText("");
                PatientCountryTxt.setText("");
                PatientDiagnosisTxt.setText("");
                PatientEmailTxt.setText("");
                PatientGenderTxt.setText("");
                PatientHNOTxt.setText("");
                PatientIDTxt.setText("");
                PatientMedicalHistoryTxt.setText("");
                PatientNameTxt.setText("");
                PatientPostalCodeTxt.setText("");
                PatientStreetNameTxt.setText("");

            }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtPatientIDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPatientIDSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPatientIDSearchActionPerformed

    private void PatientNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientNameTxtActionPerformed

    private void PatientIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientIDTxtActionPerformed

    private void PatientStreetNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientStreetNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientStreetNameTxtActionPerformed

    private void PatientContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientContactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientContactTxtActionPerformed

    private void PatientDiagnosisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientDiagnosisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientDiagnosisTxtActionPerformed

    private void PatientBloodGroupTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientBloodGroupTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientBloodGroupTxtActionPerformed

    private void PatientBloodPressureTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientBloodPressureTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientBloodPressureTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PatientAgeLabel;
    private javax.swing.JTextField PatientAgeTxt;
    private javax.swing.JLabel PatientBloodGroupLabel;
    private javax.swing.JTextField PatientBloodGroupTxt;
    private javax.swing.JLabel PatientBloodPressureLabel;
    private javax.swing.JTextField PatientBloodPressureTxt;
    private javax.swing.JLabel PatientBodyTempLabel;
    private javax.swing.JTextField PatientBodyTempTxt;
    private javax.swing.JLabel PatientCityLabel;
    private javax.swing.JTextField PatientCityTxt;
    private javax.swing.JLabel PatientContactLabel;
    private javax.swing.JTextField PatientContactTxt;
    private javax.swing.JLabel PatientCountryLabel;
    private javax.swing.JTextField PatientCountryTxt;
    private javax.swing.JLabel PatientDiagnosisLabel;
    private javax.swing.JTextField PatientDiagnosisTxt;
    private javax.swing.JLabel PatientEmailLabel;
    private javax.swing.JTextField PatientEmailTxt;
    private javax.swing.JLabel PatientGenderLabel;
    private javax.swing.JTextField PatientGenderTxt;
    private javax.swing.JLabel PatientHNOLabel;
    private javax.swing.JTextField PatientHNOTxt;
    private javax.swing.JLabel PatientIDLabel;
    private javax.swing.JTextField PatientIDTxt;
    private javax.swing.JLabel PatientMedicalHistoryLabel;
    private javax.swing.JTextField PatientMedicalHistoryTxt;
    private javax.swing.JLabel PatientNameLabel;
    private javax.swing.JTextField PatientNameTxt;
    private javax.swing.JLabel PatientPostalCodeLabel;
    private javax.swing.JTextField PatientPostalCodeTxt;
    private javax.swing.JLabel PatientStreetNameLabel;
    private javax.swing.JTextField PatientStreetNameTxt;
    private javax.swing.JTextField TxtPatientIDSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
