/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.HospitalDataRecord;
import model.HospitalDetails;
import model.MedcareDataRecord;

/**
 *
 * @author deepaksharma
 */
public class UpdateHospitalDetails extends javax.swing.JPanel {

    /**
     * Creates new form UpdateHospitalDetails
     */
    HospitalDataRecord hospital_history ;
    public UpdateHospitalDetails(HospitalDataRecord hospital_history) {
        initComponents();
        this.hospital_history = hospital_history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtHospitalIDSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        HospitalNameTxt = new javax.swing.JTextField();
        HospitalCountryTxt = new javax.swing.JTextField();
        HospitalContactLabel = new javax.swing.JLabel();
        HospitalPostalCodeLabel = new javax.swing.JLabel();
        HospitalContactTxt = new javax.swing.JTextField();
        HospitalPostalCodeTxt = new javax.swing.JTextField();
        HospitalEmailLabel = new javax.swing.JLabel();
        HospitalEmailTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        HospitalStreetNameLabel = new javax.swing.JLabel();
        HospitalStreetNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HospitalCityLabel = new javax.swing.JLabel();
        HospitalIDTxt = new javax.swing.JTextField();
        HospitalCityTxt = new javax.swing.JTextField();
        HospitalNameLabel = new javax.swing.JLabel();
        HospitalCountryLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Hospital Details");

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Hospital ID:");

        TxtHospitalIDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHospitalIDSearchActionPerformed(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        HospitalContactLabel.setText("Contact:");

        HospitalPostalCodeLabel.setText("Postal Code:");

        HospitalContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalContactTxtActionPerformed(evt);
            }
        });

        HospitalEmailLabel.setText("Email:");

        HospitalEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalEmailTxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Address:");

        HospitalStreetNameLabel.setText("Street Name:");

        HospitalStreetNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalStreetNameTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("ID*:");

        HospitalCityLabel.setText("City*:");

        HospitalIDTxt.setEditable(false);
        HospitalIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalIDTxtActionPerformed(evt);
            }
        });

        HospitalNameLabel.setText("Name*:");

        HospitalCountryLabel.setText("Country:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtHospitalIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(217, 217, 217))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HospitalEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(HospitalNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospitalContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HospitalContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospitalNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospitalIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HospitalEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HospitalPostalCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalStreetNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HospitalStreetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalPostalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(TxtHospitalIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HospitalIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalNameLabel)
                            .addComponent(HospitalNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalContactLabel)
                            .addComponent(HospitalContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalEmailLabel)
                            .addComponent(HospitalEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HospitalStreetNameLabel)
                            .addComponent(HospitalStreetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HospitalCityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalCountryLabel)
                            .addComponent(HospitalCountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalPostalCodeLabel)
                            .addComponent(HospitalPostalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(372, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String name = HospitalNameTxt.getText();
        if (name.length() == 0 ){
            JOptionPane.showMessageDialog(this,"The 'Name' is a mandatory field, please provide required value.", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String city = HospitalCityTxt.getText();
        if (city.length() == 0 ){
            JOptionPane.showMessageDialog(this,"The 'City' is a mandatory field, please provide required value.", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String validate_hosp_contact = String.valueOf(HospitalContactTxt.getText());
        if (validate_hosp_contact.length() > 0 ){
            try 
                { 
                 Long.parseLong(HospitalContactTxt.getText()); 
                }  
            catch (NumberFormatException e)  
                { 
                JOptionPane.showMessageDialog(this,"The Contact is invalid, please provide the integer value only.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;}          
        } 
        
        if (validate_hosp_contact.length() != 10 ){
                JOptionPane.showMessageDialog(this,"The Contact is invalid, please provide the valid contact value.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;
        }
        
        
        String validate_hosp_mail = String.valueOf(HospitalEmailTxt.getText());
        if (!validate_hosp_mail.contains("@") && validate_hosp_mail.length() > 0  ){
            JOptionPane.showMessageDialog(this,"The email is invalid, please provide the valid mail id.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
            return;     
        } 
        
        int update_hospital_id = Integer.parseInt(HospitalIDTxt.getText()); 
        for (HospitalDetails ed : hospital_history.getHistory()){
            int hospital_id = ed.getHospital_id();
            if (update_hospital_id == hospital_id){     
                
                String hospital_name = HospitalNameTxt.getText();
                long hospital_contact = Long.parseLong(HospitalContactTxt.getText());
                String hospital_email = HospitalEmailTxt.getText();
                String hospital_streetname = HospitalStreetNameTxt.getText();
                String hospital_city = HospitalCityTxt.getText();
                String hospital_country = HospitalCountryTxt.getText();
                String hospital_postalcode = HospitalPostalCodeTxt.getText();
             
                          
                HospitalDetails UpdateHospRec = hospital_history.UpdateHospital();
                
                UpdateHospRec.setHospital_name(hospital_name);
                UpdateHospRec.setHospital_id(hospital_id);
                UpdateHospRec.setHospital_contact(hospital_contact);
                UpdateHospRec.setHospital_email(hospital_email);
                UpdateHospRec.setHospital_city(hospital_city);
                UpdateHospRec.setHospital_country(hospital_country);
                UpdateHospRec.setHospital_postal_code(hospital_postalcode);
                UpdateHospRec.setHospital_street_name(hospital_streetname);
                
                JOptionPane.showMessageDialog(this, "Hospital Details has been updated");
                
                hospital_history.DeleteHospitalDetails(ed);
                
                HospitalIDTxt.setText("");
                HospitalNameTxt.setText("");
                HospitalContactTxt.setText("");
                HospitalEmailTxt.setText("");
                HospitalStreetNameTxt.setText("");
                HospitalCityTxt.setText("");
                HospitalCountryTxt.setText("");
                HospitalPostalCodeTxt.setText("");

            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtHospitalIDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHospitalIDSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHospitalIDSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String hospital_id = String.valueOf(TxtHospitalIDSearch.getText());
        
        if (hospital_id.length() == 0 ){
            JOptionPane.showMessageDialog(this,"The search field is empty, please provide required values to search.", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (hospital_id.length() > 0 ){
            try 
                { 
                int user_hosp_id = Integer.parseInt(TxtHospitalIDSearch.getText()); 
                }  
            catch (NumberFormatException e)  
                { 
                JOptionPane.showMessageDialog(this,"The Hospital ID is invalid, please provide the integer value only.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;}          
        } 

        HospitalIDTxt.setText("");
        HospitalNameTxt.setText("");
        HospitalContactTxt.setText("");
        HospitalEmailTxt.setText("");
        HospitalStreetNameTxt.setText("");
        HospitalCityTxt.setText("");
        HospitalCountryTxt.setText("");
        HospitalPostalCodeTxt.setText("");
        
        int user_hosp_id = Integer.parseInt(TxtHospitalIDSearch.getText());
        int id_check = 0 ;
        for (HospitalDetails ed : hospital_history.getHistory()){
            int hosp_id = ed.getHospital_id(); 
            if (hosp_id == user_hosp_id){
                id_check = 1;                  
                HospitalNameTxt.setText(ed.getHospital_name());
                HospitalIDTxt.setText(String.valueOf(ed.getHospital_id()));
                HospitalCountryTxt.setText(ed.getHospital_country());
                HospitalCityTxt.setText(ed.getHospital_city());
                HospitalStreetNameTxt.setText(ed.getHospital_street_name());
                HospitalContactTxt.setText(String.valueOf(ed.getHospital_contact()));
                HospitalEmailTxt.setText(ed.getHospital_email());
                HospitalPostalCodeTxt.setText(ed.getHospital_postal_code());
            }
        }

        if (id_check != 1 ){
            JOptionPane.showMessageDialog(this,"The Hospital ID doesn't exist, please provide correct Hospital ID.", "Invalid Value", JOptionPane.WARNING_MESSAGE);
            return;
        }     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HospitalContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalContactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalContactTxtActionPerformed

    private void HospitalEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalEmailTxtActionPerformed

    private void HospitalStreetNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalStreetNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalStreetNameTxtActionPerformed

    private void HospitalIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalIDTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HospitalCityLabel;
    private javax.swing.JTextField HospitalCityTxt;
    private javax.swing.JLabel HospitalContactLabel;
    private javax.swing.JTextField HospitalContactTxt;
    private javax.swing.JLabel HospitalCountryLabel;
    private javax.swing.JTextField HospitalCountryTxt;
    private javax.swing.JLabel HospitalEmailLabel;
    private javax.swing.JTextField HospitalEmailTxt;
    private javax.swing.JTextField HospitalIDTxt;
    private javax.swing.JLabel HospitalNameLabel;
    private javax.swing.JTextField HospitalNameTxt;
    private javax.swing.JLabel HospitalPostalCodeLabel;
    private javax.swing.JTextField HospitalPostalCodeTxt;
    private javax.swing.JLabel HospitalStreetNameLabel;
    private javax.swing.JTextField HospitalStreetNameTxt;
    private javax.swing.JTextField TxtHospitalIDSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
